### ISSUE TITLE
QPDF using wmain on Windows and paths with e.g. German umlauts.

### ISSUE THREAD

**Issue by ams-tschoening** [qpdf/qpdf#298]
I tried to open a PDF file using a German umlaut and got the following error executing using `cmd.exe`:

    C:\Users\[...]>qpdf --check [...]_Bärbel_[...].pdf
    open [...]_B├ñrbel_[...].pdf: No such file or directory

`[...]` is used to strip the file name to the most important details. I compiled `qpdf` using its support for `wmain` and all of your tests passed.

Looking at the code, you are converting to UTF-8 and forwarding internally. Does that mean you are forwarding UTF-8 encoded paths to `open` as well? If so, the error is correct, UTF-8 encoded file names can't be found this way on Windows. One either needs to provide the encoding in use by the system currently or Unicode, meaning `wopen` instead of open.

https://docs.microsoft.com/en-us/cpp/c-runtime-library/reference/open-wopen?view=vs-2017

Mapping UTF-8 into the file system works on most non-Windows, because they by definition simply store individual bytes, which are most likely UTF-8 encoded. But Windows/NTFS doesn't do so, it stores UTF-16 chars.

https://stackoverflow.com/questions/2050973/what-encoding-are-filenames-in-ntfs-stored-as

The reason to switch to use `wmain` was that some of your tests are passing Unicode chars to `qpdf`, which failed without `wmain`, but succeeded with. But how you handle those arguments internally is totally up to you, while forwarding UTF-8 to `open` involves the file system and such.

**Comment by sz5000** [comment]
On Windows, UTF8 filenames needs to be re-encoded to ANSI if you do not use the unicode versions of the Windows functions. Otherwise file names with umlauts will not work. Prior to `wmain` we were able to pass ansi encoded files to qpdf and this worked because qpdf did not further encoded the files and passed them to the corresponding windows api function, but now you encode wmain arguments as UTF-8 internally and this makes things worse.

**Comment by jberkenbilt** [comment]
You're right. I overlooked the case of filenames containing Unicode characters. I will have to figure out the right way to handle both cases. Ugh. Thanks for the report.

**Comment by sz5000** [comment]
Internally it should be fine when you do a utf8 -> ANSI encoding before you pass filenames to the open method. Otherwise you have to be selective and you have to encode to ANSI only for filenames.

**Comment by ams-tschoening** [comment]
While encoding back from UTF-8 to ANSI solves this concrete problem, one most likely want to support Unicode (paths) in general internally and I guess that was your ultimate goal anyway. So instead of providing a custom `wmain` only, you might want to have a look at how `TCHAR.h` works already in Windows anyway and try to reuse parts of that.

	TCHAR.H routine	_UNICODE & _MBCS not defined	_MBCS defined	_UNICODE defined
	_tfopen	        fopen	                        fopen	        _wfopen

https://docs.microsoft.com/en-us/cpp/c-runtime-library/reference/fopen-wfopen?view=vs-2017

**Comment by jberkenbilt** [comment]
What happens with files that have characters not representable in ANSI? Are they UTF-16? I guess I will create some test cases with files that have names with special characters, handling things representable with codepage 1252 and not as separate cases.

**Comment by sz5000** [comment]
If you can, you should definitively convert utf8 encoded filenames back to `wchar_t ` and then you should use the `_wfopen` method to open files. This should be save.

On the other hand, if you have to use fopen, you should convert UTF8 filenames back to `wchar_t` and then you should use `WideCharToMultiByte` with `CP_ACP` as code page.

**Comment by jberkenbilt** [comment]
I think all uses of fopen are encapsulated in the QUtil::safe_fopen method, so converting back to wchar_t should be pretty easy. Thanks for bringing this to my attention. For me, Windows are those holes in the wall that I see the sun through, though I know it's also an operating system some people like to use their computers with.

**Comment by sz5000** [comment]
Sounds good that it seems to be easy to implement. This should make this fix quicker. Every OS has pros and cons. If you provide windows bins with this fix I can test if you like.

**Comment by jberkenbilt** [comment]
@sz5000 When https://dev.azure.com/qpdf/qpdf/_build/results?buildId=206 finishes, you can download the Windows binaries from there and test if you wish, but I have added tests to the test suite for both msvc and mingw compilers, and I think it should be fine now. It's not the most elegant code I've ever written, but QUtil::safe_fopen now converts from utf8 to `wchar_t*` in a manner that doesn't make any assumptions not already made by the way it was previously implemented.

**Comment by jberkenbilt** [comment]
I intend to release this with 8.4.1 in the next few days.

**Comment by jberkenbilt** [comment]
@sz5000 Here's the binary distributions from the latest CI build. Test if you wish, but don't feel obligated to do so. Thanks!

https://dev.azure.com/qpdf/f24ef40e-3b5d-43d6-ac5d-40e46e203e50/_apis/build/builds/206/artifacts?artifactName=distribution&api-version=5.1-preview.5&%24format=zip

**Comment by ams-tschoening** [comment]
I have problems running your new tests for this change: You are creating new test files using non-ASCII characters by copying some template file to new names. The problem is that those new names are encoded in UTF-8 and forwarded by Perl as UTF-8 encoded bytes to Windows. This results in names like the following visible in Process Monitor and the files are really created using names with individual UTF-8 bytes:

    auto-Ã¼.pdf
    16:36:02,6687986	perl.exe	13804	CreateFile	C:\Users\tschoening\[...]\qtest\qpdf\auto-Ã¼.pdf	SUCCESS	Desired Access: Generic Read/Write, Delete, Write DAC, Disposition: OverwriteIf, Options: Sequential Access, Synchronous IO Non-Alert, Non-Directory File, Attributes: A, ShareMode: None, AllocationSize: 0, OpenResult: Created

When `qpdf.exe` is actually run, that can't find the files because it's really expecting a file called `auto-ü.pdf`, because characters instead of UTF-8 bytes are forwarded to its command line. I'm somewhat sure that Perl has multiple limitations in handling Unicode in file names on Windows, because it converts to bytes under different circumstances. I can easily fix the problem when I create the test files myself e.g. using Windows Explorer, because that is capable of creating the necessary Unicode names to test for.

So, how sure are you that in your Windows-tests you are really actually testing Unicode characters for file names instead of file names using individual UTF-8 bytes and therefore wrongly succeed just because of your environment?

**Comment by jberkenbilt** [comment]
Actually, it occurred to me as I was adding the tests, and I forgot. :-( I will make sure I figure out a way to make the test reliable on Windows before releasing 8.4.1.

**Comment by jberkenbilt** [comment]
I also commented on the PR itself. I was nervous about including files in the git repo with Unicode characters in their names because I wasn't sure that was going to work reliably with all permutations.

**Comment by jberkenbilt** [comment]
I think I'm going to just come up with a more reliable way of dynamically creating the files rather than committing them. I can think of several relatively easy ways to do it. I will be sure to actually check to make sure they are doing what I want.

To be clear, does the code work for you and it's just the tests that are bad, or does the fix as I implement it still not work correctly with Unicode files? I will do some manual testing on Windows as well.

**Comment by ams-tschoening** [comment]
> [...]I wasn't sure that was going to work reliably with all permutations.

In my opinion it is very likely that GIT clients handle those things properly/better than Perl does. The official GIT clients for Windows even support Windows symlinks these days, so seem to care a lot about the platform they are currently running on. While it doesn't necessary mean anything, I wasn't able to get `File::Copy::copy` or `link` to not use individual UTF-8 bytes for the test file names even with converting to UTF-8 strings in Perl and whatever. I always ended up with needing bytes and that would introduce OS-specific code in Perl as well, makes using UTF-16le because of 0-bytes impossible to forward to Perl's internals etc.

It might additionally be of interest that I originally committed the files of my PR using TortoiseSVN and the SVN-bridge provided by GitHub, then pulled the changes using TortoiseGIT and cherry picked them with that for the PR-branch. That's a somewhat complex setup already and if that works, I wouldn't be too worried anymore. :-)

> To be clear, does the code work for you and it's just the tests that are bad, or does the fix as I implement it still not work correctly with Unicode files? I will do some manual testing on Windows as well.

I didn't test manually yesterday, but after fixing the tests with my PR those succeeded, which meant to me your code should be working. I've additionally tested manually right now starting Powershell and cmd.exe in there and things worked as well. The first test was using 8.4.0 and the second one using upcoming 8.4.1:

	PS C:\Users\[...]\out> cmd.exe
	Microsoft Windows [Version 10.0.17763.437]
	(c) 2018 Microsoft Corporation. Alle Rechte vorbehalten.

	C:\Users\[...]\out>qpdf --check "C:\Users\[...]\auto-ü.pdf"
	open C:\Users\[...]\auto-├╝.pdf: No such file or directory


	C:\Users\[...]\out>qpdf --check "C:\Users\[...]\auto-öπ.pdf"
	open C:\Users\[...]\auto-├Â¤Ç.pdf: No such file or directory


	C:\Users\[...]\out>qpdf --check "C:\Users\[...]\auto-ü.pdf"
	checking C:\Users\[...]\auto-├╝.pdf
	PDF Version: 1.3
	File is not encrypted
	File is not linearized
	No syntax or stream encoding errors found; the file may still contain
	errors that qpdf cannot detect

	C:\Users\[...]\out>qpdf --check "C:\Users\[...]\auto-öπ.pdf"
	checking C:\Users\[...]\auto-├Â¤Ç.pdf
	PDF Version: 1.3
	File is not encrypted
	File is not linearized
	No syntax or stream encoding errors found; the file may still contain
	errors that qpdf cannot detect

	C:\Users\[...]\out>

That makes me recognize that UTF-8 is still output on STDOUT, but I guess one can live with that.

**Comment by jberkenbilt** [comment]
Regarding UTF-8 in standard output, this is just ignorance on my part. What should be in the output? I guess I really need to be using wchar_t* or some std::string equivalent on Windows to be properly Unicode aware. I'll mess with it and see if I can get it to work. This should be strictly a CLI thing. The library may not behave in the best way here either as it expects filename arguments to be UTF-8 encoded which may not be naturally in a Windows environment, though I think it's reasonable and there are arguments to be made for it (see https://utf8everywhere.org/). However, I could like at using std::wstring in some places. I'm not sure. This may be more than I can really bite off for the library, particularly without committing one of the worst backward compatibility offenses of changing the semantic meaning of a specific call without changing its signature. But for the CLI, I can at least make error messages look right.

Regarding the tests, I'm not going to include files with Unicode characters in the repository period. This is non-negotiable. It's not just git. The distribution comes as a .tar.gz file that could be extracted in any number of ways on any old system. Other people package qpdf for other systems. Some commercial users or users with special compilers take the source distribution of qpdf and build it in their own environments. One of the major selling points of qpdf is that it has very few external dependencies, works on older versions of the compiler, etc. If someone wants to build qpdf on some embedded platform with some antiquated compiler (which people do and tell me about), then I don't want to do something like needlessly adding files with non-ASCII characters to the source distribution that causes headaches for these people. I have previously made other similar changes to help with weird environments, such as renaming some files in the test suite that used to contain ".." in their names as this was causing problems for some obscure environment. Hopefully this sheds some more light on my reasoning.

I am very grateful for our dialog on this. You are doing a big part in helping to make qpdf work better in environments I don't usually use and for raising my awareness on some issues, plus your test caught a mistake in my testing that could have undermined the ability of the tests to effectively ensure that I was doing the right thing. Any "push back" is simply my explaining my rationale. I remain open to being convinced that I am wrong at all times. :-)

**Comment by jberkenbilt** [comment]
@ams-tschoening I have pushed up improvements to the tests, added a TODO entry, and added some notes to the docs about this. For now, I am not going to undertake fully fixing handling of Unicode file names in all cases (error messages, CLI output, etc.) because qpdf's API really predates my thinking about this issue. In UNIX environments, just using UTF-8 pretty much does the right thing. In Windows, it has to be more explicit. However, I do believe that qpdf 8.4.1 properly supports Unicode filenames in Windows based on my automated and manual tests in various permutations, and the re-coded tests should be more reliable. I'm afraid we will have to live with the goofy encoding of file names in output for now. Thanks again for your help with this issue. Sorry I can't provide a perfect solution, but at least it will work to actually operate on these files.

**Comment by jberkenbilt** [comment]
I'm going to close this, but please feel free to continue commenting or to re-open if there is still a problem. I'm going to try to get 8.4.1 out.

**Comment by sz5000** [comment]
I'll be testing your changes in a few days after completing some of my other assignments.

**Comment by jberkenbilt** [comment]
@sz5000 Thanks. I've released 8.4.1, so please test that and report any issues if it's not working. There are rough edges in things like output/error messages, but the functionality should be there.

**Comment by ams-tschoening** [comment]
> For now, I am not going to undertake fully fixing handling of Unicode file names in all cases (error messages, CLI output, etc.)[...]

It might be that MS is going to address this in future already, because with the last major versions of Windows 10 they are improving the console regarding making it more compatible with terminals on Linux and UTF-8. While I'm running 1809 already and still see individual UTF-8-bytes instead of characters in `cmd.exe`, form my understanding while they improved Unicode-support under the hood, UTF-8 is still going to be addressed in future. The following blog posts are pretty interesting:

https://devblogs.microsoft.com/commandline/windows-command-line-introducing-the-windows-pseudo-console-conpty/

https://devblogs.microsoft.com/commandline/windows-command-line-unicode-and-utf-8-output-text-buffer/

> I've released 8.4.1, so please test that and report any issues if it's not working.

The tests of 8.4.1 are working for me now, thanks. I just omitted large file related ones, which worked before already.

**Comment by sz5000** [comment]
I've tested version 8.4.1 regarding the unicode issue under windows and as far as I can see, unicode filenames with umlauts works now and qpdf no longer outputs an error. Thank you for fixing.
